name: Sync Fork with Upstream

on:
  # schedule:  # Commented out for safety (destructive action); uncomment and adjust if needed
  #   - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:  # Manual trigger (recommended for testing destructive syncs)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          ref: master  # Your fork's target branch
          fetch-depth: 0  # Full history for resets
          token: ${{ secrets.GITHUB_TOKEN }}  # Default token (no PAT needed)

      - name: Debug Git Status (Before Sync)
        run: |
          git status
          git branch -a
          git remote -v
          ls -la .github/workflows/  # Verify your workflow files exist

      - name: Sync with Upstream (Protecting Workflows, No Force-Push)
        env:
          UPSTREAM_REPO: https://github.com/gookie-dev/StepDaddyLiveHD.git  # Full URL of upstream repo (update if needed)
          UPSTREAM_BRANCH: master  # Upstream branch to copy from
          TARGET_BRANCH: master  # Your fork's branch to update
        run: |
          # Add upstream remote
          git remote add upstream $UPSTREAM_REPO || true
          git fetch upstream

          # Backup your workflow files
          mkdir -p temp-workflows
          cp -r .github/workflows/* temp-workflows/ || true

          # Reset to upstream (discards your changes)
          git checkout $TARGET_BRANCH
          git reset --hard upstream/$UPSTREAM_BRANCH

          # Restore custom workflow files
          cp -r temp-workflows/* .github/workflows/ || true
          rm -rf temp-workflows

          # Add restored workflows
          git add .github/workflows/ || true

          # Commit changes
          git commit -m "Synced from upstream, preserving custom workflows" || echo "No changes to commit"

          # Safe push (no --force; may fail if divergences prevent it)
          git push origin $TARGET_BRANCH || echo "Push failed - manual resolution needed (e.g., resolve conflicts or use force locally)"

      - name: Debug Git Status (After Sync)
        run: |
          git status
          git log -n 5  # Verify commits
          git remote -v
          ls -la .github/workflows/  # Confirm workflows are preserved
