name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes; adjust as needed
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork  # NEW: This checks out your fork's code, required for Git operations
        uses: actions/checkout@v4  # Use v4 for the latest stable version
        with:
          fetch-depth: 0  # Fetches full history to handle merges properly
          token: ${{ secrets.GITHUB_TOKEN }}  # Or your PAT if needed

      - name: Upstream Sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}  # Default; switch to a PAT secret for more permissions
          upstream_sync_repo: gookie-dev/StepDaddyLiveHD  # e.g., 'octocat/Hello-World'
          upstream_sync_branch: master  # Upstream branch to sync from
          target_sync_branch: master  # Your fork's branch to update
          upstream_pull_args: '--ff-only'  # Fast-forward to avoid conflicts
          target_branch_push_args: '--force'  # Optional: Use cautiously for overwrites
          test_mode: false  # Set to true for testing without changes
          git_pull_rebase_config: 'true'  # Optional: Helps with rebase during sync
